# Project Information
site_name: WeeDocs
site_description: WeeDocs 是一个在线静态文档，整合了个人及 WeeCine 团队编写的 IT 及 AI 系统学习资料。
site_author: WeeCine
site_url: https://docs.weecine.com/
theme:
  name: material

# Copyright
copyright: 'Copyright &copy; 2023 - 2024 WeeCine'

nav:
- 简介:
    - 开始: index.md
    - 关于: about.md
    - 加入: join.md
    - 致谢: thanks.md
- 计算机入门: 
    - 系统: ITin/system.md
    - 命令行: ITin/cmd.md
- 编程语言: 
    - Python: Program/python.md
- 智能学习:
    - 文生文: AIin/docs.md
    - 文生图: AIin/pics.md
- 电子电路:
    - 电路入门: dianzi/index.md
- 红石电路:
    - 序: Redstone/index.md
    - Part1:
        - 第一章：常见红石元件: Redstone/Part1/1.md
        - 第二章：红石电路连接基础: Redstone/Part1/2.md
        - 第三章：中继器进阶理论: Redstone/Part1/3.md
        - 第四章：比较器进阶理论: Redstone/Part1/4.md
        - 第五章：红石刻及计算基础: Redstone/Part1/5.md
        - 第六章：高频原理: Redstone/Part1/6.md
    - Part2:
        - 第一章：AFK与全自动: Redstone/Part2/1.md
        - 第二章：光照亮度与刷怪机制: Redstone/Part2/2.md
        - 第三章：运输设计原理: Redstone/Part2/3.md
        - 第四章：农业催生原理: Redstone/Part2/4.md
        - 第五章：生物处死原理: Redstone/Part2/5.md
        - 第六章：强加载与弱加载: Redstone/Part2/6.md
    - Part3:
        - 第一章：红石电路进阶理论: Redstone/Part3/1.md
        - 第二章：计时器及其原理: Redstone/Part3/2.md
        - 第三章：随机数原理: Redstone/Part3/3.md
        - 第四章：无电路传导: Redstone/Part3/4.md
        - 第五章：循环电路: Redstone/Part3/5.md
        - 第六章：比较电路: Redstone/Part3/6.md
- 天码秋令营: 
    - 命令行: SkyCode/Part1.md
    - Git: SkyCode/Part2.md
    - 命令行工具及其安装: SkyCode/Part3.md
    - Anaconda下载及安装: SkyCode/Part4.md
    - Jupyter入门体验: SkyCode/Part5.md
    - ComfyUI入门体验: SkyCode/Part6.md